### ISSUE TITLE
Support for Astro v2

### ISSUE THREAD

**Issue by fflaten** [delucis/astro-auto-import#10]
Currently getting peer conflicts when building using `Astro v2.0.0-beta.2` due to `^1.0.0` peer dependency.

**Comment by delucis** [comment]
Thanks for the note! I don’t think there’s anything in v2 that should impact this plugin, so we should be good to loosen that restriction.

Would you be up for submitting a PR to change this? This line should probably be `^1.0.0 || ^2.0.0-beta` to allow early adopters to try it out against the current beta releases.

https://github.com/delucis/astro-auto-import/blob/fa29b462171325bf9bcb86a84a9836d1104f6f80/packages/astro-auto-import/package.json#L41
