### ISSUE TITLE
astro-auto-import stoped working after astro update to 2.5

### ISSUE THREAD

**Issue by guizmo** [delucis/astro-auto-import#18]
When runing the "astro build" command, i get the following error message in the console
```
[astro:jsx] /path/to/project/src/pages/page-quizz.mdx: Could not render `Quiz`. No matching import has been found for `Quiz`.
```
<img width="923" alt="Screenshot 2023-05-24 at 14 58 43" src="https://github.com/delucis/astro-auto-import/assets/699063/469e6ae9-5c15-466f-a26e-74df65b03d06">

It used to work under Astro 2.1
If i import manually the "Quizz" component, i don't get the error...

**Comment by delucis** [comment]
Thanks for the report! Not sure what’s happening, but will take a look.

**Comment by delucis** [comment]
Hi @guizmo — haven’t been able to reproduce this. Could you share your repo’s before/after branches or a minimal reproduction (e.g. on StackBlitz: https://astro.new/minimal)?

**Comment by guizmo** [comment]
Hi @delucis , thanks for looking into it, i have managed to make a simple example work... so there is obviously something wrong with my component

I'll investigate... sorry for the troubles

**Comment by guizmo** [comment]
I found the issue, i removed the remarkPlugins form the mdx conf
its extended from the markdown conf anyway

```
mdx({
      // remarkPlugins: [remarkMermaid, remarkGFM],
      drafts: false,
      gfm: true
    }),
```

**Comment by delucis** [comment]
Ah, gotcha. Thanks for the update!
