### ISSUE TITLE
Adding MDOC

### ISSUE THREAD

**Issue by teinett** [delucis/astro-auto-import#31]
It would be nice to work with MDOC files too. 
In this case we can use Keystatic CMS admin and easy global import of components.

**Comment by delucis** [comment]
Does Markdoc support imports? I think you need to configure the Markdoc config file which sets up what tags are available, so is essentially already doing what this plugin does.

**Comment by delucis** [comment]
Closing this as I believe Markdoc’s existing design of [defining components in `markdoc.config.mjs`](https://docs.astro.build/en/guides/integrations-guide/markdoc/#render-components) already does this and I don’t think `astro-auto-import` has anything to add here.
